### PR TITLE
Search Page UI updated

### LINKED ISSUE #70: Design: UI revamp of complete app
### Description:
UI revamp of the app based on the designs in [figma file](https://www.figma.com/file/QP1vkEh0a7joS484npSShD/Git-Repo-Viewer?type=design&node-id=0%3A1&mode=design&t=IBWYg9jsP9hqBEDr-1).

### Sub Issues:
- [x] Create an app icon #82    -  @Yash-Waghmare 
- [x] Make app drawer #78   - @Lomesh21 
- [x] Adding new themes and Search Page UI updation #77  - @SarveshChavan 
- [x] Creating profile page #81  - @Lomesh21 
- [x] Contributors Page UI #88  - @Lomesh21 
- [x] Bookmark Page UI #89  - @Yash-Waghmare 
- [ ] About Us Page UI #92 - @Yash-Waghmare 

### Resource:
- [Material 3 Design](https://m3.material.io/) 
- [Flutter UI docs](https://docs.flutter.dev/ui) 

### Note:
I expect progress, so one assigned has to report every 3 days

### PR DESCRIPTION
**Pull request by SarveshChavan**
Linked Issue #77 

### Changes made
Changed the UI according to the new flutter design, also due to some bugs and errors the color scheme is changed a little bit. 

### How does the solution address the problem
This PR will focus on the UI enhancement of the search repo page and will give the user a better experience of using the App.

### CODE REVIEW

**Comment by SarveshChavan** [comment]
@dk-a-dev sorry for the delay. Can you please review it ASAP so that this contribution will be counted in hacktoberfest ?

**Comment by dk-a-dev** [comment]
Yup sure buddy i am on it, I also want to get it merge before tomo
plz be active if I post a review to make quick fixes if any

**Comment by dk-a-dev** [comment]
- the new UI doesnt look neat and there bugs in colour scheme
image
- contributors page card not updated 
image
- the repo card needs a lot of improvement, its not like one in design
image
@SarveshChavan

**Comment by dk-a-dev** [comment]
@SarveshChavan if u are struggling with something let me knw, i can help, @Lomesh21 is also willing to help

**Comment by SarveshChavan** [comment]
Sorry for the mistake but when I click wo dark theme in my machine the theme is changing properly and also the issue with repo card is because we can't fet h the followers and the contact details from our api (the response of get repos method). Also the slimy widget has some constraints of its own such as the cards height should be 150 minimum and if I increase it for the other 2 fields(followers and contact) the card height get increased and when we increase the slimy widget card height it produces an extra blank card after each slimy widget. But I'll still try to make it possible and I'll let you know. I'll change it tomorrow and also will take the pull to avoid conflict.

**Comment by SarveshChavan** [comment]
image
image

The switch button working fine the theme is getting changed, @dk-a-dev review the PR, and also the changes that have been made in the contributors page and drawer need to be changed according to theme.

**Review by dk-a-dev — APPROVED** [review]
Great Job dude, u changed the feel of the app its looks great
Small fixes 
- colour scheme of buttons in contributors' page(its out of scope of this PR but :))
image
- change theme button on dark mode coinciding with bg
image
what u can do choose a pastel shade of blue(although this issue could be of material3 itself)

@SarveshChavan Good Job I will be mergin this 
you can make small fixes in other pr

**Pull request merged**
