### PR TITLE
Profile page is added 

### LINKED ISSUE #81: Creation of Profile Page
Creation of profile page as user logged in the app, user will see the details.

Page will be created as per figma design.

### PR DESCRIPTION
**Pull request by Lomesh21**
Profile page is added and the app drawer switch color is also changed as it hides due to background color

Resolves #81

### CODE REVIEW

**Comment by Lomesh21** [comment]
@dk-a-dev Review the page

**Review by dk-a-dev — APPROVED** [review]
Awesome!! Great implementation of pfp design

**Comment by Lomesh21** [comment]
Hey @dk-a-dev, the contributor page is not fetching the contributors, Can you check it and give any suggestion about that, because i want to make theme updation in contributors page

**Comment by dk-a-dev** [comment]
@Lomesh21 its fine for me
pull and fetch from master
So u want contributors page UI issue

**Pull request merged**
