### PR TITLE
Contributor page is updated as per design

### LINKED ISSUE #88: Integrate Contributor page with theme
Contributor Page modification according to figma design and integrate with theme change

### PR DESCRIPTION
**Pull request by Lomesh21**
# Contributor page updated

All the updations are done.
Change theme is integrated in contributor page

Resolves #88

### CODE REVIEW

**Comment by Lomesh21** [comment]
@dk-a-dev plz review the PR

**Review by dk-a-dev — APPROVED** [review]
Merged!!😀

**Comment by Lomesh21** [comment]
@dk-a-dev  thanks bro, for giving an opportunity of working in the app

**Comment by dk-a-dev** [comment]
Keep contributing to open-source projects
Happy Hacktoberfest🧡 and Happy Halloween🎃

**Pull request merged**
