### PR TITLE
revert : app flow reverted

### PR DESCRIPTION
**Pull request by dk-a-dev**
Reverts IEEE-VIT/hackfest-flutter#72

- Refer [Issue on Mermaid JS Github](https://github.com/mermaid-js/mermaid/issues/4388)
- Reason Given : Diagram error not found. this error has been fixed in our newer releases (Github is few release behind).

### CODE REVIEW

**Comment by SarveshChavan** [comment]
@dk-a-dev you have reverted this PR will this contribution be counted, I guess it will give my contribution to hactober fest sone problem.

**Comment by dk-a-dev** [comment]
@SarveshChavan yup buddy it could but i tried my best to solve the problem...it all depends on hacktoberfest PR reviewer

**Comment by SarveshChavan** [comment]
Then can we just add the app flow that I created which didn't had the mermaid js

**Comment by dk-a-dev** [comment]
> Then can we just add the app flow that I created which didn't had the mermaid js

No sorry, that was rejected

**Pull request merged**
