### PR TITLE
App Drawer created

### PR DESCRIPTION
**Pull request by Lomesh21**
App drawer created succesfully,
Profile photo container, List tiles, and animated switch is added and also the route funtionality working by giving only routename in Custom ListTile
functionality of app drawer is remained as
1 . Profile page is not created
2 . Sign out funtionality needs sign in authentication which is yet to implement 
3 . Change theme needs the change in whole theme provider so first the light theme should be ready on which we are working right now

#78 is resolved

### CODE REVIEW

**Comment by Lomesh21** [comment]
@dk-a-dev Please review the PR...

**Comment by dk-a-dev** [comment]
@Lomesh21 I reviewed the design good job, there are a lot of minor bugs like colour scheme, const keywords addition, and alignment issues but for now keep on working I am waiting for PR of the app workflow then I will merge it feel free to extend the scope of this one and add more commits also hacktoberfest is coming to its end so make sure to make this PR perfect so that I can merge asap and u can guys can then keep contributing to the issue even after fest which I believe you should

**Review by dk-a-dev — APPROVED** [review]
Ready to merge 
I hope u are aware that 
ur next task is to integrate theme and also make pfp page

**Comment by Lomesh21** [comment]
@dk-a-dev Yep, Integrating theme means the dark theme and light theme integration, right?

**Comment by dk-a-dev** [comment]
yes use change theme to change theme of the app, also ask @SarveshChavan if he making any changes that might effect ur work

**Pull request merged**
