### PR TITLE
App icon added

### LINKED ISSUE #82: Add App Icon
**Add the app Icon**
Create and add the app icon for the Hackfest application.

**Additional context**
The issue is related to #70

### PR DESCRIPTION
**Pull request by Yash-Waghmare**
### App Icon

Added app icon 

### Linked issues

Resolves #82

### CODE REVIEW

**Comment by Yash-Waghmare** [comment]
Hey, @dk-a-dev, what's the progress on this PR?

**Comment by dk-a-dev** [comment]
@Yash-Waghmare Sorry to kept u waiting this icon was rejected 
can u make an iteration of a pumpkin carved with "H" in Halloween styles scary font

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare Sorry to kept u waiting this icon was rejected can u make an iteration of a pumpkin carved with "H" in Halloween styles scary font

Actually, I have used current year font for hacktoberfest

**Comment by Yash-Waghmare** [comment]
will you give me an example of what is wanted ?

**Comment by dk-a-dev** [comment]
@Yash-Waghmare bro i got an awesome design try to implement this one as an app icon
Please try to finish it by today
here is the reference
iteration-3
I know u worked hard on last icon but unfortunately it got rejected, please work on this one and I will merge ur pr by today for sure 
Happy Halloween🎃

**Comment by dk-a-dev** [comment]
> will you give me an example of what is wanted ?

refer sent message @Yash-Waghmare

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare bro i got an awesome design try to implement this one as an app icon Please try to finish it by today here is the reference iteration-3 I know u worked hard on last icon but unfortunately it got rejected, please work on this one and I will merge ur pr by today for sure Happy Halloween🎃

Great, so should I use this logo directly without modifying it further?

**Comment by Yash-Waghmare** [comment]
And, also can you send the link of this logo to download

**Comment by dk-a-dev** [comment]
yes u can use it directly, but feel free to experiment with the colours of the logo if you can, if not use it directly

**Comment by Yash-Waghmare** [comment]
Yaa, got it, thanks

**Comment by Yash-Waghmare** [comment]
OIG


Hey, how is this

**Comment by dk-a-dev** [comment]
> OIG
> 
> 
> Hey, how is this 

Do not seem like a logo
Use the earlier one only
I don't have a link 
Do u use discord I can send u there drop me hi
> Dk_A_Dev#6560

**Comment by dk-a-dev** [comment]
> yes u can use it directly, but feel free to experiment with the colours of the logo if you can, if not use it directly
> also the image given is itself a cutout shaped logo try to extract the pumpkin use bing ai tools for purpose
> @Yash-Waghmare 

Ig u can download that from GitHub also

**Comment by Yash-Waghmare** [comment]
> > yes u can use it directly, but feel free to experiment with the colours of the logo if you can, if not use it directly
> > also the image given is itself a cutout shaped logo try to extract the pumpkin use bing ai tools for purpose
> > @Yash-Waghmare
> 
> Ig u can download that from GitHub also

Downloaded, I will do it immediately.

**Comment by Yash-Waghmare** [comment]
Added the required icon

**Review by dk-a-dev — CHANGES_REQUESTED** [review]
Great Job @Yash-Waghmare adding icon to the app , its accepted

**Review by dk-a-dev — APPROVED** [review]
Ready to merge

**Pull request merged**
