### PR TITLE
About Us page updated

### LINKED ISSUE #92: About us Page UI
**Description**
Create an about us page that will follow the dart theme.

**Additional context**
Issue is related to #70

### PR DESCRIPTION
**Pull request by Yash-Waghmare**
### Description
The About Us page is updated with proper theming

### Linked issues
Resolves  sub-issue #92 
Also Closes  Base Issue #70

### CODE REVIEW

**Review by dk-a-dev — CHANGES_REQUESTED** [review]
- About Us page not updated a/c to the design in figma file
- Error in retrieving IEEE(2).png
image
@Yash-Waghmare low-quality PRs will not be merged, Please make About Us Page as expected refer #70 figma file

**Comment by Yash-Waghmare** [comment]
> * About Us page not updated a/c to the design in figma file
> * Error in retrieving IEEE(2).png
>   image
>   @Yash-Waghmare low-quality PRs will not be merged, Please make About Us Page as expected refer [Design: UI revamp of complete app #70](https://github.com/IEEE-VIT/hackfest-flutter/issues/70) figma file

Yes, let me check, I will make the changes.

**Comment by Yash-Waghmare** [comment]
Sorry I haven't checked the Figma file, I will make the changes and let you know

**Comment by Yash-Waghmare** [comment]
image

Here on the visit button which link should be redirected github repo link or IEEE link.

**Comment by dk-a-dev** [comment]
Redirect to GitHub and on clicking IEEE image redirect to website

**Comment by dk-a-dev** [comment]
Also the text which is there should be added if u can figure out a way to add that text

**Comment by Yash-Waghmare** [comment]
> Also the text which is there should be added if u can figure out a way to add that text

Yaa, I will try it.

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev, I have updated the about us page, will you please go through it.

**Review by dk-a-dev — APPROVED** [review]
Good job buddy great work merging ASAP

**Comment by dk-a-dev** [comment]
yup its being checked

**Pull request merged**
