### PR TITLE
Fix: enhance contributors page UX #49

### PR DESCRIPTION
**Pull request by Imsurajr**
changed the colour of the following widgets:
1) Progress Indicator
2) Contributors count
3) Floating Action Button

to improve User Experience, as the color is same as the color which is used in home screen's elevated button.

Linked Issue: #49

### CODE REVIEW

**Comment by dk-a-dev** [comment]
Your PR is under review

**Comment by dk-a-dev** [comment]
Hey great work on changing the colours of elements on the page, can you add an animation if no contributors are searched @Imsurajr

**Review by dk-a-dev — CHANGES_REQUESTED** [review]
Great work so far 👍
Can u add an animation either custom or through a package that when no contributors are searched

**Comment by Imsurajr** [comment]
While contributions are getting searched, there is progress indicator already, where do you want me to add new animations?

**Comment by dk-a-dev** [comment]
> While contributions are getting searched, there is progress indicator already, where do you want me to add new animations?

That loading spinner is there already because...
```
 @override
  void initState() {
    super.initState();
    getContributors(username: 'IEEE-VIT', repository: 'hacktoberfest-flutter')
        .then((cards) {
      setState(() {
        cardList = cards;
      });
    });
  }
```
But there is an issue contributors are not fetched, so I want is
when fetching: loading spinner
if failed: animation
if not fetching(and not failed offcourse): animation(or text saying search repo in search tab)

I can extend your stated issue if u want to work on this, if not no problem I will assign this to another person
You can ask for help from me or I can also assign one more person to help you if u want 
please le me know, I hope I cleared ur doubt

**Comment by Imsurajr** [comment]
I will work on this, but currently I want to complete my hacktoberfest commits and this repo is excluded, so i can work on this issue but later.

**Comment by dk-a-dev** [comment]
> I will work on this, but currently I want to complete my hacktoberfest commits and this repo is excluded, so i can work on this issue but later.

I want someone to work on it now, so I what I think best would be , to approve ur pr, and put up a new issue for this

**Review by dk-a-dev — APPROVED** [review]

**Comment by dk-a-dev** [comment]
PR closed, conflicts resolved badly, cant be fixed

**Pull request closed without merging**
