### PR TITLE
Bookmark page UI redesigned.

### LINKED ISSUE #89: Bookmark Page UI
**Description**
Redesigning the Bookmark page UI.

**Describe the solution you'd like**
According to the new design format, the new bookmark page will be integrated.

**Additional context**
The issue is related to #70

### PR DESCRIPTION
**Pull request by Yash-Waghmare**
# Description

this issue redesigns the bookmark page UI

## Linked issues

Resolves #89

### CODE REVIEW

**Review by dk-a-dev — CHANGES_REQUESTED** [review]
- the dark theme background and card colour clashin refer figma file for design
image

**Comment by dk-a-dev** [comment]
rest everything seems fine please fix this @Yash-Waghmare

**Comment by dk-a-dev** [comment]
@Yash-Waghmare please fix this one by evening

**Comment by Yash-Waghmare** [comment]
Yes, I will do the needful.

**Comment by Yash-Waghmare** [comment]
Hey, @dk-a-dev, I have resolved the issue.

**Review by dk-a-dev — APPROVED** [review]
Ready to Merge😀

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev, this PR is not considered as hacktoberfest contribution, I think because of hacktoberfest label is not there, what can we do in such a case now?

**Comment by dk-a-dev** [comment]
Can u send SS of what hacktoberfest website gives

**Comment by Yash-Waghmare** [comment]
> Can u send SS of what hacktoberfest website gives

image

**Comment by dk-a-dev** [comment]
I will look into it

**Pull request merged**
